version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - ENV=dev
    volumes:
      - /home/user/app:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"

